---
title: "DS202- Lab#3"
output: html_document
date: "2023-10-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
df <- read.csv("https://raw.githubusercontent.com/fivethirtyeight/data/master/avengers/avengers.csv", stringsAsFactors = FALSE)
```

```{r}
head(df)
```

```{r}
names(df)
```

```{r}
summary(df)
```

```{r}
str(df)
```

```{r}
library(tidyverse)

deaths <- df %>%
  pivot_longer(starts_with("Death"),
               names_to = "Time",
               values_to = "Died") %>%
  select(URL,Time, Died)
```

```{r}
maxdeaths <- deaths %>% 
  mutate(
    Time = parse_number(Time)
  ) %>% 
  filter(Died != '') %>% 
  group_by(URL, Died) %>% 
  summarise(
    Time = max(Time),
    .groups = 'drop'
  )
```

```{r}
Returns <- df %>%
  pivot_longer(starts_with("Return"),
               names_to = "Time",
               values_to = "Return") %>%
  select(URL,Time, Return)

```

```{r}
maxReturns <- Returns %>% 
  mutate(
    Time = parse_number(Time)
  ) %>% 
  filter(Return != '') %>% 
  group_by(URL, Return) %>% 
  summarise(
    Time = max(Time),
    .groups = 'drop'
  )

```


```{r}
average_deaths <- deaths %>%
  filter(Died != '') %>% 
  group_by(URL, Died) %>% 
  summarise(
    Time = max(Time)
  )
```

```{r}
(" the quote that I choose is:  Out of 173 listed Avengers, my analysis found that 69 had died at least one time after they joined the team.5 That’s about 40 percent of all people who have ever signed on to the team. Let’s put it this way: If you fall from four or five stories up, there’s a 50 percent chance you die. Getting a membership card in the Avengers is roughly like jumping off a four-story building. 
 To figure out this quote I compare the five deaths by time as shown below")
```

```{r}
ggplot(deaths, aes(x = Time, fill = Died)) +
  geom_bar(position = "dodge") +
  labs(title = "Deaths Over Time",
       x = "Time",
       y = "Count") +
  theme_minimal()
```

```{r}
ggplot(Returns, aes(x = Time, fill = Return)) +
  geom_bar(position = "dodge") +
  labs(title = "Returns Over Time",
       x = "Time",
       y = "Count") +
  theme_minimal()
```


```{r}
("I got confused of the previous two plots. It is clear yes and no, but what is the representation of the pink color? Does it mean something else like died because of sickness or in case of return means unknown or what?")
```


```{r}


```












```{r}
